// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		Center: typeof import('./../components/header/components/center.vue')['default']
		ChangeLanguage: typeof import('./../components/change-language.vue')['default']
		Footer: typeof import('./../components/footer.vue')['default']
		Header: typeof import('./../components/header/header.vue')['default']
		Left: typeof import('./../components/header/components/left.vue')['default']
		Right: typeof import('./../components/header/components/right.vue')['default']
		VideoMV: typeof import('./../components/videoMV.vue')['default']
	}
}

export {}
